name: cheetah_demo
description: Demonstrates how to use the cheetah plugin.

publish_to: 'none'

version: 2.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.9
  flutter_voice_processor: 1.1.2
  cheetah_flutter:
    path: ../../binding/flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/test_resources/
    - assets/test_resources/audio_samples/
    - assets/test_resources/model_files/
