name: cheetah_demo
description: Demonstrates how to use the cheetah plugin.

publish_to: 'none'

version: 3.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  path_provider: ^2.0.9
  flutter_voice_processor: 1.1.2
  cheetah_flutter:
    path: ../../binding/flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/test_resources/
    - assets/test_resources/audio_samples/
    - assets/test_resources/model_files/
